language: python
python:
  - "3.6"
  - "3.7"
 before_install:
  - sudo apt-get update
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
