language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
#  - pip install -r requirements.txt #(should work from install_requires)
  - pip install pytest
# command to run tests
script:
  - pytest test/test_pynm.py::TestBasic
